project:
  type: website
  output-dir: docs
website:
  title: "website1"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - test1.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

